// The one piece of WebGPU boilerplate shared across every week from here
// on: requesting a device and wiring a canvas to it. Everything else —
// shaders, buffers, pipelines, render passes — stays written out in full
// in each week's own page, since that's the material actually being
// taught. This file exists only so "does your browser support WebGPU"
// isn't retyped on every page.

export function isSupported() {
  return typeof navigator !== "undefined" && "gpu" in navigator;
}

// A friendly fallback UI for browsers without WebGPU (Chrome/Edge 113+
// required), instead of a raw exception.
export function unsupportedNotice() {
  const div = document.createElement("div");
  div.style.padding = "16px";
  div.style.borderRadius = "8px";
  div.style.background = "var(--theme-background-alt, #f5f5f5)";
  div.style.border = "1px solid #d99";
  div.innerHTML = `<strong>WebGPU isn't available in this browser.</strong>
    <p style="margin-top:6px">This page needs Chrome or Edge 113+ (WebGPU enabled by default). Firefox and Safari have only partial support as of 2026.</p>`;
  return div;
}

// Requests an adapter and device, throwing a descriptive error rather
// than letting `requestAdapter()` returning null propagate as a
// confusing crash deeper in setup code.
export async function requestDevice(options) {
  if (!isSupported()) throw new Error("WebGPU is not supported in this browser.");
  const adapter = await navigator.gpu.requestAdapter(options);
  if (!adapter) throw new Error("No suitable GPU adapter found.");
  const device = await adapter.requestDevice();
  return {adapter, device};
}

// Creates and configures a canvas's WebGPU context — step 2 of every
// week's "hello triangle"-shaped setup.
export function configureCanvas(canvas, device) {
  const context = canvas.getContext("webgpu");
  const format = navigator.gpu.getPreferredCanvasFormat();
  context.configure({device, format, alphaMode: "opaque"});
  return {context, format};
}

// Repeatedly halves a source canvas (using the browser's own high-quality
// image resampling) to build a full mip chain as plain 2D canvases, down
// to 1x1 — Week 6's mipmap pyramid, built on the CPU for clarity rather
// than generated by a GPU render pass.
export function generateMipCanvases(sourceCanvas) {
  const canvases = [sourceCanvas];
  let {width: w, height: h} = sourceCanvas;
  let prev = sourceCanvas;
  while (w > 1 || h > 1) {
    w = Math.max(1, w >> 1);
    h = Math.max(1, h >> 1);
    const next = document.createElement("canvas");
    next.width = w;
    next.height = h;
    const ctx = next.getContext("2d");
    ctx.imageSmoothingEnabled = true;
    ctx.imageSmoothingQuality = "high";
    ctx.drawImage(prev, 0, 0, w, h);
    canvases.push(next);
    prev = next;
  }
  return canvases;
}

// Uploads a list of same-content, halving-resolution canvases (from
// generateMipCanvases, or just [canvas] for a single-level texture) as
// one GPUTexture's mip chain.
export function textureFromMipCanvases(device, mipCanvases, {label} = {}) {
  const base = mipCanvases[0];
  const texture = device.createTexture({
    label,
    size: [base.width, base.height],
    format: "rgba8unorm",
    mipLevelCount: mipCanvases.length,
    usage: GPUTextureUsage.TEXTURE_BINDING | GPUTextureUsage.COPY_DST | GPUTextureUsage.RENDER_ATTACHMENT
  });
  mipCanvases.forEach((canvas, mipLevel) => {
    device.queue.copyExternalImageToTexture({source: canvas}, {texture, mipLevel}, [canvas.width, canvas.height]);
  });
  return texture;
}
